{"code": 0, "msg": "FAIL", "task_id": "202208291028350510842", "task_name": "whole process", "create_time": "20220829102835051162", "error": "Traceback (most recent call last):\n  File \"/home/jit/service/mpc/driver/task.py\", line 60, in persist\n    r = self.__future.result()\n  File \"/usr/lib/python3.6/concurrent/futures/_base.py\", line 425, in result\n    return self.__get_result()\n  File \"/usr/lib/python3.6/concurrent/futures/_base.py\", line 384, in __get_result\n    raise self._exception\n  File \"/usr/lib/python3.6/concurrent/futures/thread.py\", line 56, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/home/jit/service/mpc/SrcCode/main_dynamic_function.py\", line 29, in start_mpc\n    dv = DynamicVariables(config_cpt)\n  File \"/home/jit/service/mpc/SrcCode/Source/dynamic_function.py\", line 72, in __init__\n    self.input_analysis()\n  File \"/home/jit/service/mpc/SrcCode/Source/dynamic_function.py\", line 199, in input_analysis\n    nested_length = [self.meta_js['components'][i]['data_len'][:] for i in range(modules_len)] # related input data length\n  File \"/home/jit/service/mpc/SrcCode/Source/dynamic_function.py\", line 199, in <listcomp>\n    nested_length = [self.meta_js['components'][i]['data_len'][:] for i in range(modules_len)] # related input data length\nKeyError: 'data_len'\n"}